name: ci pipeline

on:
  - push
  - pull_request

jobs:
  main:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Dependency installation
        run: |
          npm ci
          npm run build --if-present
      - name: Linting
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: Coverage
        run: |
          npm run coverage
          # npm run codecov
